config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/home'

  resources :benefices
  resources :zones
  resources :addresses
  resources :customers
  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :zone,  required: false
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses
									# reject_if: proc {|attributes| attributes['name'].blank?},
									# allow_destroy:true


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    # @customers = Customer.all
    @customers= Customer.includes(:addresses).all
    @addres = Address.all

    @map_hash = Gmaps4rails.build_markers(@addres) do |address, marker|
      marker.lat address.latitude
      marker.lng address.longitude
      marker.infowindow [address.address,"</br>", address.latitude,address.latitude].join('-')
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    # @customers= Customer.includes(:addresses).all
      @customers= Customer.includes(:addresses).find(params[:id])
      @addres = Address.where(customer_id: @customers.id).first
      @map_hash = Gmaps4rails.build_markers(@addres) do |address, marker|
      marker.lat address.latitude
      marker.lng address.longitude
      marker.infowindow [address.address,"</br>", address.latitude,address.latitude].join('-')
    end

  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.addresses.build
  end

  # GET /customers/1/edit
  def edit
    # @customer.addresses.build
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:n_socio, :nombre, :apellido, addresses_attributes: [:id, :address, :latitude, :longitude])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
  <div class="banner">

<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="row">
  <div class="col-md-4 col-xs-12">
      <div class="form-group">
            <%= form.label :n_socio, "Numero de socio:" %>
            <%= form.text_field :n_socio,autofocus: true,:required => true, :class=>"form-control input-sm" %>  
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-xs-12">
    <div class="form-group">

    <%= form.label :nombre, "Nombre:" %>
            <%= form.text_field :nombre,autofocus: true,:required => true, :class=>"form-control input-sm" %>  
    </div>

  </div>
    <div class="col-md-6 col-xs-12">
    <div class="form-group">
      <%= form.label :apellido, "Apellido:" %>
                <%= form.text_field :apellido,autofocus: true,:required => true, :class=>"form-control input-sm" %>  
          </div>    
    </div>
</div>

<div class="row">
  <div class="col-md-12 col-xs-12">
    <div class="form-group">
          <%= form.fields_for :addresses do |ubicacion|%>
              <%=ubicacion.label :address, "Direccion:"%><br/>
              <%= ubicacion.text_area :address, class: "form-control input-sm" ,rows: 2%>
          <%end%>
    </div>
  </div>
</div>






  <div class="actions">
           <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        <i class="fa fa-floppy-o " aria-hidden="true"></i>
         Guardar
        <% end %>


  </div>
<% end %>

</div>

app/views/customers/edit.html.erb
<div class="container">
<div class="banner">
   <h2>Editar Cliente</h2>
</div>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

</div>

app/views/customers/index.html.erb
<div class="container">

<div class="banner">
   <h2>Clientes</h2>
</div>
                                                                                  
  <div class="table-responsive banner">          
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Num. de Socio</th>
        <th>Apellido - Nombre</th>
        <th>Dirección</th>
        <th>Estado</th>
        <th>Acciones</th>
      
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.n_socio %></td>
        <td><%= customer.apellido %>, <%= customer.nombre %></td>
        <% customer.addresses.each do |direccion| %>
          <% if (direccion.address)%>
             <td><%= direccion.address %></td>
          <%end%>
        <%end%>
        <td>status</td>
        <td>

            <%= link_to '<i class="fa fa-eye" ></i>'.html_safe, customer_path(customer), class: "btn btn-default btn-view"  %>

            <%= link_to '<i class="fa fa-pencil" ></i>'.html_safe, edit_customer_path(customer), class: "btn btn-default btn-edit"  %>

             <%= link_to '<i class="fa fa-trash-o" ></i>'.html_safe,  customer, method: :delete, data: { confirm: 'Seguro que desea eliminar el cliente?' }, class: "btn btn-default btn-delete"  %>
                
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>
  </div>

  <div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="map-system">
      <div id="map" class="map"></div>
    </div> 

  </div>
  </div>

</div>



<script type="text/javascript">
  createMap(<%=raw @map_hash.to_json %>, 1);
</script>

app/views/customers/new.html.erb
<div class="container">
<div class="banner">
   <h2>Nuevo Cliente</h2>
</div>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>


</div>

app/views/customers/show.html.erb
<div class="container">

<div class="banner">
	<!--  <div class="pull-right"> -->
<!-- accion editar -->
  <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar'.html_safe, edit_customer_path(@customer),  class: 'btn btn-edit-show'%>  <span>
<!-- accion volver -->
<%= link_to '<i class="fa fa-undo" aria-hidden="true"></i> Volver'.html_safe, customers_path,  class: 'btn btn-undo'%>  <span>
             
        
<!-- 	 </div> -->
</div>

	<div class="banner">

		<div class="row">
			<div class="col-md-6 col-xs-12">
				<div class="form-group">
					<strong>Número de socio:</strong>
					<%= @customer.n_socio %>
				</div>
				<div class="form-group">
					<strong>Socio:</strong>
					<%= @customer.apellido %>, <%= @customer.nombre %>
				</div>
				<div class="form-group">
					<strong>Direccion:</strong>
					  <% @customer.addresses.each do |direccion| %>
						<%= direccion.address %>
					  <%end%>
					
					
				</div>
				<div class="form-group">
					<strong>Estado:</strong>
					<%= @customer.estado %>
				</div>
			</div>
			
			<div class="col-md-6 col-xs-12">
				<div class="map_mini">
				
						<div id="map" class="map"></div>
					 
				</div>
			</div>

		</div>
	</div>
</div>





<script type="text/javascript">
  createMap(<%=raw @map_hash.to_json %>, 2);
</script>