config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/home'

  resources :benefices
  resources :zones
  resources :addresses
  resources :customers
  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/zone.rb
class Zone < ApplicationRecord
	has_many :coordinate_zones, :dependent => :delete_all
	has_many :customers
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :js
   
  # GET /zones
  # GET /zones.json
  def index
    @zones= Zone.all

    @polyjson = []
    schoolpoints = []
    @zones.each do |zone|
      CoordinateZone.where(:zone_id => zone.id).each do |point|
         schoolpoints << { :zone => point.zone_id,  :lng => point.longitud, :lat => point.latitud}
      end
    end
    puts "********schoolpoints***********"
    puts schoolpoints.inspect

    @polyjson = schoolpoints
    @polyjson = @polyjson.to_json
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create

    has = params["area"].to_json
    data_has =  JSON.parse(has)
    @zone = Zone.new();
    @zone.nombre_zona = params["nombre_zona"]
    @zone.color = params["color"]

    respond_to do |format|
      if @zone.save
       
        data_has.each do |geo|
          @coordenada = CoordinateZone.new()
          geo.each do |data|
            @coordenada.zone_id = @zone.id
            @coordenada.latitud =  data["lat"].to_f
            @coordenada.longitud = data["lng"].to_f 
          end
          @coordenada.save
        end

        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.js 
        # format.js { render js: "window.location.href=#{ directories_path }" }
        format.json { render :show, status: :created, location: @zone }
         
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update

    # @zone = Zone.find(params[:id])
    # @zone.nombre_zona = params["nombre_zona"]
    @coordenada = CoordinateZone.where('zone_id = ?', @zone.id)
    @coordenada.each do |cz|
      cz.destroy
    end

    respond_to do |format|
      if @zone.update #(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.js 
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to action: "index" }
      format.json { head :no_content }
      #testing
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      # params.require(:zone) #.permit( :zone, :nombre_zona, :color)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
  <div class="banner"> 
    <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-3">
          <%= form_with(model: zone, local: true) do |form| %>


          <div class="field">
            <%= form.label :nombre_zona,class: "control-label" %>
            <%= form.text_field :nombre_zona, id: :zone_nombre_zona, class: "form-control" %>
          </div>
          <br>
          <div class="form-group">
            <label for="sel1">Color de la zona:</label>
            <select class="form-control" id="zone_color">
              <option value="0099e5">1</option>
              <option value="ff4c4c">2</option>
              <option value="34bf49">3</option>
            </select>
          </div>
          <br />

      </div>
        <div class="col-md-9 col-sm-9 col-xs-9">
            <div class="map-system">
                <div id="map_zone" class="map"></div>
            </div> 

        </div>
    </div>

<% end %>

</div>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<input id="id"  type="text">




  <div class="banner"> 

	<div class="row">
		<div class="col-md-9 col-sm-9 col-xs-9"> 

			<button  id="guardarEdicionZona" class="btn btn-default pull-right">Guardar Cambios Zona</button>
			<button id="btnmarcar" class="btn btn-default pull-right">Marcar zona</button>
		</div>
	</div>
</div>
<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

<script type="text/javascript">
document.getElementById("id").value = <%= @zone.id  %>;
$('#btnmarcar').attr("disabled", true);
$('#guardarEdicionZona').attr("disabled", true);
  createMapZone();
</script>

app/views/zones/index.html.erb
<div class="container">
  <div class="banner">
   <h2>Zonas</h2>
</div>

  <div class="table-responsive banner">          
      <table class="table table-striped table-bordere.jsd">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombre zona</th>
          <th>Color</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

       <% @zones.each do | zone | %>
        <tr>
          <td><%= zone.id %></td>
          <td><%= zone.nombre_zona %></td>
          <td><%= zone.color %></td>
          <td > 
            <div class="pull-right">
              <%= link_to '<i class="fa fa-eye" ></i>'.html_safe, zone_path(zone), class: "btn btn-default btn-view"  %>
              <%= link_to '<i class="fa fa-pencil" ></i>'.html_safe, edit_zone_path(zone), class: "btn btn-default btn-edit"  %>
              <%= link_to '<i class="fa fa-trash-o" ></i>'.html_safe,  zone, remote: true,  method: :delete, data: { confirm: 'Seguro que desea eliminar el cliente?' }, class: "btn btn-default btn-delete"  %>
            </div>
          </td>
        </tr>
       <% end %>

      </tbody>
    </table>
  </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="map-system">
                <div id="map" class="map"></div>
            </div> 

        </div>
    </div>

<br>

<%= link_to 'New Zone', new_zone_path %>
  
</div>


<script type="text/javascript">
  viewZonesAll(<%=raw @polyjson %>, 1);
</script>

app/views/zones/new.html.erb
<div class="container">
<div class="banner">
   <h2>Nueva Zona</h2>
</div>

<%= render 'form', zone: @zone %>


  <div class="banner"> 

	<div class="row">
		<div class="col-md-9 col-sm-9 col-xs-9"> 

			<button  id="guardarDatosZona" class="btn btn-default pull-right">Guardar Zona</button>
			<button id="btnmarcar" class="btn btn-default pull-right">Marcar zona</button>
		</div>
	</div>
</div>
<script type="text/javascript">
$('#btnmarcar').attr("disabled", true);
$('#guardarDatosZona').attr("disabled", true);
  createMapZone();
</script>

<%= link_to 'Back', zones_path %>



</div>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre zona:</strong>
  <%= @zone.nombre_zona %>
</p>

<p>
  <strong>Color:</strong>
  <%= @zone.color %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>